export const TRADES = [
  'Plumbing',
  'Electrical',
  'HVAC',
  'Carpentry',
  'Framing',
  'Concrete',
  'Roofing',
  'Drywall',
  'Painting',
  'Welding',
  'Masonry',
  'Flooring',
  'Tile',
  'Equipment Operator',
  'Laborer',
  'Superintendent',
  'Project Manager',
] as const