export const TRADES = [
  'Plumbing',
  'Pipefitting',
  'Steamfitting',
  'HVAC',
  'Refrigeration',
  'Sheet Metal',
  'Fire Sprinkler',
  'Fire Protection',
  'Medical Gas',
  'Electrical',
  'Low Voltage',
  'Fire Alarm',
  'Security Systems',
  'Building Controls',
  'Data & Communications',
  'Solar',
  'Carpentry',
  'Framing',
  'Finish Carpentry',
  'Cabinetry',
  'Concrete',
  'Masonry',
  'Roofing',
  'Siding',
  'Gutters',
  'Drywall',
  'Painting',
  'Insulation',
  'Flooring',
  'Tile',
  'Glazing',
  'Doors & Hardware',
  'Welding',
  'Ironwork',
  'Structural Steel',
  'Millwright',
  'Industrial Maintenance',
  'Rigger',
  'Excavation',
  'Underground Utilities',
  'Pipelaying',
  'Grading',
  'Paving',
  'Directional Drilling',
  'Equipment Operator',
  'Heavy Equipment',
  'Landscaping',
  'Irrigation',
  'Fencing',
  'Maintenance Technician',
  'Mechanic',
  'CDL Driver',
  'Garage Door',
  'Handyman',
  'Laborer',
  'General Labor',
  'Superintendent',
  'Project Manager',
] as const
